get-appxpackage *skypeapp* | remove-appxpackage
get-appxpackage *zunemusic* | remove-appxpackage
get-appxpackage *zune* | remove-appxpackage
get-appxpackage *messaging* | remove-appxpackage
get-appxpackage *solitaire* | remove-appxpackage
get-appxpackage *wallet* | remove-appxpackage
get-appxpackage *bingfinance* | remove-appxpackage
get-appxpackage *bing* | remove-appxpackage
get-appxpackage *zunevideo* | remove-appxpackage
get-appxpackage *bingnews* | remove-appxpackage
get-appxpackage *commsphone* | remove-appxpackage
get-appxpackage *windowsphone* | remove-appxpackage
get-appxpackage *phone* | remove-appxpackage
get-appxpackage *bingsports* | remove-appxpackage
get-appxpackage *sway* | remove-appxpackage
get-appxpackage *xbox* | remove-appxpackage
get-appxpackage *spotify* | remove-appxpackage
get-appxpackage *facebook* | remove-appxpackage
get-appxpackage *tiktok* | remove-appxpackage
