@ECHO OFF
msiexec /i "C:\Work\Chained MSI\SMARTEducationSoftware.msi" INSTALL_BOARD=1 INSTALL_NOTEBOOK=1 NB_PROD_KEY=NC2IDSADWBCK4GDS5ANC2B ACTIVATE_LICENSE=1 FULL_GALLERY="" LAT_CONTENT="" INSTALL_UNSIGNED_DRIVERS=1 ENABLE_STPCS="" LAUNCH_SYSTEM_MENU="" /qb

